### ISSUE TITLE
Updates needed since last Rusticata release

### ISSUE THREAD

**Issue by pevandenburie** [rusticata/pcap-parse#1]
Hi,

It seems few dependencies have not been updated since last Rusticata release. To fix compilation issues:

    pnet = "0.22.0"

and change ```SnmpParser``` to ```SNMPParser```, ```SnmpV3Parser``` to ```SNMPv3Parser```.

Thanks!

**Comment by chifflier** [comment]
Hi,
Thanks for the report (and the PR). FYI, I'm currently working on another binary, not yet released but which will replace entirely pcap-parse - I'll release it as soon as possible.
In the meantime, I'll update pcap-parse so it builds.

**Comment by pevandenburie** [comment]
Great! Thanks 👍
